package example.Object;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class Order {
    WebDriver driver;
    public Order(WebDriver driver) {
        this.driver = driver;
    }

    String url = "https://automationexercise.com/";// url
    By g1 = By.xpath("//*[@id=\"header\"]/div/div/div/div[2]/div/ul/li[1]/a");
    By g2 = By.xpath("/html/body/section[2]/div/div[1]/div[2]/div[1]/div[2]/div/div[1]/div[1]/a");
    By g3 = By.xpath("//*[@id=\"header\"]/div/div/div/div[2]/div/ul/li[3]/a");
    By g4 = By.xpath("//a[@class=\"btn btn-default check_out\"]");
    By g5 = By.xpath("//*[@id=\"checkoutModal\"]/div/div/div[2]/p[2]/a/u");
    By g6 = By.xpath("//input[@type=\"text\"]");
    By g7 = By.xpath("//input[@data-qa=\"signup-email\"]");
    By g8 = By.xpath("//button[@data-qa=\"signup-button\"]");
    By g9 = By.xpath("//input[@id=\"id_gender2\"]");
    By g10 = By.xpath("//input[@type=\"password\"]");
    By g11 = By.xpath("//select[@id=\"days\"]");
    By g12 = By.xpath("//select[@id=\"months\"]");
    By g13 = By.xpath("//select[@id=\"years\"]");
    By g14 = By.xpath("//input[@name=\"newsletter\"]");
    By g15 = By.xpath("//input[@name=\"optin\"]");
    By g16 = By.xpath("//input[@data-qa=\"first_name\"]");
    By g17 = By.xpath("//input[@data-qa=\"last_name\"]");
    By g18 = By.xpath("//input[@data-qa=\"company\"]");
    By g19 = By.xpath("//input[@data-qa=\"address\"]");
    By g20 = By.xpath("//input[@data-qa=\"address2\"]");
    By g21 = By.xpath("//input[@data-qa=\"state\"]");
    By g22 = By.xpath("//input[@data-qa=\"city\"]");
    By g23 = By.xpath("//input[@data-qa=\"zipcode\"]");
    By g24 = By.xpath("//input[@data-qa=\"mobile_number\"]");
    By g25 = By.xpath("//button[@data-qa=\"create-account\"]");
    By g26 = By.xpath("//*[@id=\"form\"]/div/div/div/h2/b");
    By g27 = By.xpath("//a[@data-qa=\"continue-button\"]");
    By g28 = By.xpath("//*[@id=\"header\"]/div/div/div/div[2]/div/ul/li[10]/a");
    By g29 = By.xpath("//*[@id=\"cart_items\"]/div/div[2]/h2");
    By g30 = By.xpath("//*[@id=\"cart_items\"]/div/div[4]/h2");
    By g31 = By.xpath("//textarea[@class=\"form-control\"]");
    By g32 = By.xpath("//a[@href=\"/payment\"]");
    By g33 = By.xpath("//input[@name=\"name_on_card\"]");
    By g34 = By.xpath("//input[@name=\"card_number\"]");
    By g35 = By.xpath("//input[@name=\"cvc\"]");
    By g36 = By.xpath("//input[@name=\"expiry_month\"]");
    By g37 = By.xpath("//input[@name=\"expiry_year\"]");
    By g38 = By.xpath("//button[@id=\"submit\"]");
    By g39 = By.xpath("//*[@id=\"success_message\"]/div");
    By g40 = By.xpath("//a[@href=\"/delete_account\"]");
    By g41 = By.xpath("//*[@id=\"form\"]/div/div/div/h2/b");
    By g42 = By.xpath("//a[@data-qa=\"continue-button\"]");
    By g43 = By.xpath("//a[@href=\"/login\"]");
    By g44 = By.xpath("/html/body/section[2]/div/div/div[2]/div[1]/div[2]/div/div[2]/ul/li/a");
    By g45 = By.xpath("//a[@href=\"/view_cart\"]");
    By g46 = By.xpath("//*[@id=\"cartModal\"]/div/div/div[2]/p[2]/a/u");
    By g47 = By.xpath("//a[@href=\"/login\"]");
    By s32 = By.xpath("//input[@data-qa=\"login-email\"]");
    By s33 = By.xpath("//input[@data-qa=\"login-password\"]");
    By s34 = By.xpath("//button[@data-qa=\"login-button\"]");
    By g48 = By.xpath("/html/body/section[2]/div[1]/div/div[2]/div[1]/div[1]/div/div/div[2]/p[2]/a");
    By g49 = By.xpath("//a[@class=\"cart_quantity_delete\"]");
    By g50 = By.xpath("//*[@id=\"empty_cart\"]/p/b");
    By g51 = By.xpath("//*[@id=\"address_delivery\"]/li[1]/h3");
    By g52 = By.xpath("//*[@id=\"address_invoice\"]/li[1]/h3");



    public void registerwhilecheckout() throws InterruptedException {
        driver.get(url);
        driver.findElement(g1).getText();
        System.out.println("verify home page");
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("window.scrollBy(0,500)");
        driver.findElement(g2).click();
        Thread.sleep(1000);
        driver.findElement(g48).click();
        driver.findElement(g3).getText();
        System.out.println("Verify Cart page");
        driver.findElement(g4).click();
        driver.findElement(g5).click();
        driver.findElement(g6).sendKeys("Gayatri Raina");
        driver.findElement(g7).sendKeys("gayatriraina1@gmail.com");
        driver.findElement(g8).click();
        Thread.sleep(4000);
        WebElement r = driver.findElement(g9);
        r.click();
        driver.findElement(g10).sendKeys("Gayu@12345");
        js.executeScript("window.scrollBy(0,1000)");
        Select dropdown = new Select(driver.findElement(g11));
        dropdown.selectByVisibleText("28");
        Select dropdown1 = new Select(driver.findElement(g12));
        dropdown1.selectByVisibleText("March");
        Select dropdown2 = new Select(driver.findElement(g13));
        dropdown2.selectByVisibleText("1997");
        WebElement check1 = driver.findElement(g14);
        check1.click();
        WebElement check2 = driver.findElement(g15);
        check2.click();
        js.executeScript("window.scrollBy(0,700)");
        driver.findElement(g16).sendKeys("Gayatri");
        driver.findElement(g17).sendKeys("Raina");
        driver.findElement(g18).sendKeys("abc");
        driver.findElement(g19).sendKeys("Kharadi");
        driver.findElement(g20).sendKeys("Bypass");
        driver.findElement(g21).sendKeys("Maharashtra");
        driver.findElement(g22).sendKeys("Pune");
        driver.findElement(g23).sendKeys("411014");
        driver.findElement(g24).sendKeys("6006243294");
        driver.findElement(g25).click();
        driver.findElement(g26).getText();
        System.out.println("Verify Account Created!");
        driver.findElement(g27).click();
        driver.findElement(g28).getText();
        System.out.println("Verify Logged in as username");
        driver.findElement(g3).click();
        driver.findElement(g4).click();
        driver.findElement(g29).getText();
        System.out.println("Verify Address Details");
        js.executeScript("window.scrollBy(0,1000)");
        driver.findElement(g30).getText();
        System.out.println("Verify review your order");
        driver.findElement(g31).sendKeys("abcxyz");
        driver.findElement(g32).click();
        Thread.sleep(1000);
        driver.findElement(g33).sendKeys("Gayatri Raina");
        driver.findElement(g34).sendKeys("1234567890098765");
        driver.findElement(g35).sendKeys("999");
        driver.findElement(g36).sendKeys("09");
        driver.findElement(g37).sendKeys("2027");
        driver.findElement(g38).click();
        driver.findElement(g39).getText();
        System.out.println("Verify Success message");
        driver.findElement(g40).click();
        driver.findElement(g41).getText();
        System.out.println("Verify Account Deleted!");
        driver.findElement(g42).click();

    }

    public void registerbeforecheckout() throws InterruptedException {
        driver.get(url);
        driver.findElement(g1).getText();
        System.out.println("verify home page");
        driver.findElement(g43).click();
        driver.findElement(g6).sendKeys("Gayatri Raina");
        driver.findElement(g7).sendKeys("gayatriraina2@gmail.com");
        driver.findElement(g8).click();
        Thread.sleep(4000);
        WebElement r = driver.findElement(g9);
        r.click();
        driver.findElement(g10).sendKeys("Gayu@12345");
        JavascriptExecutor js1 = (JavascriptExecutor) driver;
        js1.executeScript("window.scrollBy(0,1000)");
        Select dropdown = new Select(driver.findElement(g11));
        dropdown.selectByVisibleText("28");
        Select dropdown1 = new Select(driver.findElement(g12));
        dropdown1.selectByVisibleText("March");
        Select dropdown2 = new Select(driver.findElement(g13));
        dropdown2.selectByVisibleText("1997");
        WebElement check1 = driver.findElement(g14);
        check1.click();
        WebElement check2 = driver.findElement(g15);
        check2.click();
        js1.executeScript("window.scrollBy(0,700)");
        driver.findElement(g16).sendKeys("Gayatri");
        driver.findElement(g17).sendKeys("Raina");
        driver.findElement(g18).sendKeys("abc");
        driver.findElement(g19).sendKeys("Kharadi");
        driver.findElement(g20).sendKeys("Bypass");
        driver.findElement(g21).sendKeys("Maharashtra");
        driver.findElement(g22).sendKeys("Pune");
        driver.findElement(g23).sendKeys("411014");
        driver.findElement(g24).sendKeys("6006243294");
        driver.findElement(g25).click();
        driver.findElement(g26).getText();
        System.out.println("Verify Account Created!");
        driver.findElement(g27).click();
        driver.findElement(g28).getText();
        System.out.println("Verify Logged in as username");
        js1.executeScript("window.scrollBy(0,700)");
        driver.findElement(g44).click();
        driver.findElement(g46).click();
        driver.findElement(g45).getText();
        System.out.println("Verify Cart page");
        driver.findElement(g4).click();
        driver.findElement(g29).getText();
        System.out.println("Verify Address Details");
        js1.executeScript("window.scrollBy(0,1000)");
        driver.findElement(g30).getText();
        System.out.println("Verify review your order");
        driver.findElement(g31).sendKeys("abcxyz");
        driver.findElement(g32).click();
        Thread.sleep(1000);
        driver.findElement(g33).sendKeys("Gayatri Raina");
        driver.findElement(g34).sendKeys("1234567890098765");
        driver.findElement(g35).sendKeys("999");
        driver.findElement(g36).sendKeys("09");
        driver.findElement(g37).sendKeys("2027");
        driver.findElement(g38).click();
        driver.findElement(g39).getText();
        System.out.println("Verify Success message");
        driver.findElement(g40).click();
        driver.findElement(g41).getText();
        System.out.println("Verify Account Deleted!");
        driver.findElement(g42).click();
    }

    public void loginbeforecheckout() throws InterruptedException {
            driver.get(url);
            driver.findElement(g1).getText();
            System.out.println("verify home page");
            driver.findElement(g47).click();
            driver.findElement(s32).sendKeys("gayatriraina@gmail.com");
            driver.findElement(s33).sendKeys("Gayu@12345");
            driver.findElement(s34).click();
            driver.findElement(g28).getText();
            System.out.println("Verify Logged in as username");
            driver.findElement(g2).click();
            Thread.sleep(1000);
            driver.findElement(g48).click();
            driver.findElement(g3).getText();
            System.out.println("Verify Cart page");
            driver.findElement(g4).click();
            driver.findElement(g29).getText();
            System.out.println("Verify Address Details");
            JavascriptExecutor js1 = (JavascriptExecutor) driver;
            js1.executeScript("window.scrollBy(0,1000)");
            driver.findElement(g30).getText();
            System.out.println("Verify review your order");
            driver.findElement(g31).sendKeys("abcxyz");
            driver.findElement(g32).click();
            driver.findElement(g33).sendKeys("Gayatri Raina");
            driver.findElement(g34).sendKeys("1234567890098765");
            driver.findElement(g35).sendKeys("999");
            driver.findElement(g36).sendKeys("09");
            driver.findElement(g37).sendKeys("2027");
            driver.findElement(g38).click();
            driver.findElement(g39).getText();
            System.out.println("Verify Success message");
            driver.findElement(g40).click();
            driver.findElement(g41).getText();
            System.out.println("Verify Account Deleted!");
            driver.findElement(g42).click();
    }

    public void removeproduct() throws InterruptedException {
        driver.get(url);
        driver.findElement(g1).getText();
        System.out.println("verify home page");
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("window.scrollBy(0,500)");
        driver.findElement(g2).click();
        Thread.sleep(1000);
        driver.findElement(g48).click();
        driver.findElement(g3).getText();
        System.out.println("Verify Cart page");
        driver.findElement(g49).click();
        driver.findElement(g50).getText();
        System.out.println("Verify Cart is Empty");
    }

    public void verifyaddressincheckoutpage() throws InterruptedException {
        driver.get(url);
        driver.findElement(g1).getText();
        System.out.println("verify home page");
        driver.findElement(g47).click();
        driver.findElement(g6).sendKeys("Gayatri Raina");
        driver.findElement(g7).sendKeys("gayatriraina4@gmail.com");
        driver.findElement(g8).click();
        Thread.sleep(4000);
        WebElement r = driver.findElement(g9);
        r.click();
        driver.findElement(g10).sendKeys("Gayu@12345");
        JavascriptExecutor js1 = (JavascriptExecutor) driver;
        js1.executeScript("window.scrollBy(0,1000)");
        Select dropdown = new Select(driver.findElement(g11));
        dropdown.selectByVisibleText("28");
        Select dropdown1 = new Select(driver.findElement(g12));
        dropdown1.selectByVisibleText("March");
        Select dropdown2 = new Select(driver.findElement(g13));
        dropdown2.selectByVisibleText("1997");
        WebElement check1 = driver.findElement(g14);
        check1.click();
        WebElement check2 = driver.findElement(g15);
        check2.click();
        js1.executeScript("window.scrollBy(0,700)");
        driver.findElement(g16).sendKeys("Gayatri");
        driver.findElement(g17).sendKeys("Raina");
        driver.findElement(g18).sendKeys("abc");
        driver.findElement(g19).sendKeys("Kharadi");
        driver.findElement(g20).sendKeys("Bypass");
        driver.findElement(g21).sendKeys("Maharashtra");
        driver.findElement(g22).sendKeys("Pune");
        driver.findElement(g23).sendKeys("411014");
        driver.findElement(g24).sendKeys("6006243294");
        driver.findElement(g25).click();
        driver.findElement(g26).getText();
        System.out.println("Verify Account Created!");
        driver.findElement(g27).click();
        driver.findElement(g28).getText();
        System.out.println("Verify Logged in as username");
        js1.executeScript("window.scrollBy(0,700)");
        driver.findElement(g44).click();
        driver.findElement(g46).click();
        driver.findElement(g45).getText();
        System.out.println("Verify Cart page");
        driver.findElement(g4).click();
        driver.findElement(g51).getText();
        System.out.println("Verify Delivery Address");
        driver.findElement(g52).getText();
        System.out.println("Verify Billing address");
        driver.findElement(g40).click();
        driver.findElement(g41).getText();
        System.out.println("Verify Account Deleted!");
        driver.findElement(g42).click();
    }
}
